### ISSUE TITLE
Can "fast_imas_IPOL" read TIF files?

### ISSUE THREAD

**Issue by mmacferrin** [rdguez-mariano/fast_imas_IPOL#1]
Hello, I'm currently using the "fast_imas_IPOL" executable in a University research project for geo-locating airborne images against satellite imagery.

My question: are there any plans to develop "fast_imas_IPOL" to read any other image formats besides PNG files? All of our airborne & satellite images are TIF files, geoTIFF specifically (TIF with geolocation info in the header). We *can* convert them to PNGs and that's what we're doing so far, but given the hundreds of terabytes of TIF files we have, this would be a large waste of disk space.

So, a three-part request:

1) If it does support TIF format and I simply haven't discovered how to use it, could I get a primer on how to do that? So far the executable works for PNG files but breaks for TIF files.

2) If it doesn't support TIF, are there any plans in the works to support that?

3) If there aren't plans to support TIF formats, would it be possible to get some pointers on where specifically in the source code we could look to create a branch and add that functionality?

**Comment by rdguez-mariano** [comment]
Hello,

Indeed that functionality is of great use. So, I’ve added it myself by using the [GDAL](http://www.gdal.org/) library. 

Please take a look at the README.md file for [a proper installation of GDAL on ubuntu](https://github.com/rdguez-mariano/fast_imas_IPOL#activating-gdal) and the [new optional input arguments for fast_imas_IPOL](https://github.com/rdguez-mariano/fast_imas_IPOL#reading-geospatial-data).

Best Regards,
Mariano Rodríguez

**Comment by mmacferrin** [comment]
Mariano,

This is fantastic, thank you so much! I use GDAL extensively in our work, so installing it on the Ubuntu platform is not a problem. That was an extremely quick turnaround, thank you so much for doing that!

- Mike
